{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nmrxiv-app.fullname" . }}-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  defaultBackend:
    service:
      name: {{ include "nmrxiv-app.fullname" . }}
      port:
        number: {{ .Values.service.port }}
{{- end }}