{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vibspecdb.fullname" . }}-migrate
  annotations:
    "helm.sh/hook": post-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  activeDeadlineSeconds: {{ .Values.migrate.timeout }}
  template:
    spec:
      containers:
      - name: {{ template "vibspecdb.fullname" . }}-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: 
          - sh
          - -c 
          - {{ .Values.migrate.cmd }}
        envFrom:
          - configMapRef:
              name: {{ .Values.EnvConfigMapRef.name }}
          - secretRef:
              name: {{ .Values.EnvSecretRef.name }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
