apiVersion: v1
appVersion: "v0.27.1"
description: A Helm chart for the Meilisearch search engine
name: meilisearch
version: 0.1.42
icon: https://res.cloudinary.com/meilisearch/image/upload/v1597822872/Logo/logo_img.svg
home: https://github.com/meilisearch/meilisearch-kubernetes/charts
maintainers:
    - name: Nisha Sharma
      email: nisha.sharma@uni-jena.de
