apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmrxiv-doc-gke-deployment
  labels:
    app: nmrxiv-docs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nmrxiv-docs
  template:
    metadata:
      labels:
        app: nmrxiv-docs
    spec:
      containers:
      - name: nmrxiv-docs
        image: eu.gcr.io/PROJECT_ID/IMAGE:TAG